# Generated by Django 3.0.6 on 2020-05-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.SlugField(default='test-deck-1', unique=True),
            preserve_default=False,
        ),
    ]
