# Generated by Django 3.0.6 on 2020-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_deck_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
