# Generated by Django 3.0.6 on 2020-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20200517_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.SlugField(),
        ),
    ]
