# Generated by Django 3.0.6 on 2020-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20200518_1913'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('slug', 'user'), name='unique_slug_user'),
        ),
    ]
