# Generated by Django 3.0.6 on 2020-05-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_auto_20200527_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashcards.Deck'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('front', 'deck'), name='unique_front_deck'),
        ),
    ]
